export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST "
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const EDIT_CART_REQUEST = "ADD_TO_CART_REQUEST "
export const EDIT_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const EDIT_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const DELETE_CART_REQUEST = "ADD_TO_CART_REQUEST "
export const DELETE_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const DELETE_CART_FAILURE = "ADD_TO_CART_FAILURE"

