export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const UPDATE_GIOLOCATION = "UPDATE_GIOLOCATION"
export const UPDATE_CUISINE = "UPDATE_CUISINE"

export const FETCH_RESTAURANTS_DATA_REQUEST = "FETCH_RESTAURANTS_DATA_REQUEST"
export const FETCH_RESTAURANTS_DATA_SUCCESS = "FETCH_RESTAURANTS_DATA_SUCCESS"
export const FETCH_RESTAURANTS_DATA_FAILURE = "FETCH_RESTAURANTS_DATA_FAILURE"

