export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const UPDATE_GIOLOCATION = "UPDATE_GIOLOCATION"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const UPDATE_CUISINE = "UPDATE_CUISINE"
export const CHANGE_ACTIVE_PAGE = "CHANGE_ACTIVE_PAGE"

export const FETCH_GIO_LOCATION = "FETCH_GIO_LOCATION"

export const FETCH_RESTAURANTS_DATA_REQUEST = "FETCH_RESTAURANTS_DATA_REQUEST"
export const FETCH_RESTAURANTS_DATA_SUCCESS = "FETCH_RESTAURANTS_DATA_SUCCESS"
export const FETCH_RESTAURANTS_DATA_FAILURE = "FETCH_RESTAURANTS_DATA_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE"

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST"
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS"
export const DELETE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE"


