export const VERIFY_USER_REGISTER_EMAIL_FAILURE = "VERIFY_USER_REGISTER_EMAIL_FAILURE"

export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST"
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS"
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE"

export const LOGIN_USERS_REQUEST = "LOGIN_USERS_REQUEST"
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_FAILURE = "LOGIN_USERS_FAILURE"

export const REMOVE_ERROR = "REMOVE_ERROR"
export const LOGOUT_USER = "LOGOUT_USER"