export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST";
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS";
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE";

export const LOGIN_USERS_REQUEST = "LOGIN_USERS_REQUEST";
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS";
export const LOGIN_USERS_FAILURE = "LOGIN_USERS_FAILURE";

export const LOGIN_WITH_GOOGLE_REQUEST = "LOGIN_WITH_GOOGLE_REQUEST";
export const LOGIN_WITH_GOOGLE_SUCCESS = "LOGIN_WITH_GOOGLE_SUCCESS";
export const LOGIN_WITH_GOOGLE_FAILURE = "LOGIN_WITH_GOOGLE_FAILURE";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILURE = "ADD_ADDRESS_FAILURE";

export const EDIT_ADDRESS_REQUEST = "EDIT_ADDRESS_REQUEST";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAILURE = "EDIT_ADDRESS_FAILURE";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

export const FETCH_USER_DATA__REQUEST = "FETCH_USER_DATA__REQUEST";
export const FETCH_USER_DATA__SUCCESS = "FETCH_USER_DATA__SUCCESS";
export const FETCH_USER_DATA__FAILURE = "FETCH_USER_DATA__FAILURE";

export const ADD_PAYMENT_CARD_REQUEST = "ADD_PAYMENT_CARD_REQUEST";
export const ADD_PAYMENT_CARD_SUCCESS = "ADD_PAYMENT_CARD_SUCCESS";
export const ADD_PAYMENT_CARD_FAILURE = "ADD_PAYMENT_CARD_FAILURE";

export const REMOVE_ERROR = "REMOVE_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST ";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST ";
export const EDIT_CART_SUCCESS = "EDIT_CART_SUCCESS";
export const EDIT_CART_FAILURE = "EDIT_CART_FAILURE";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST ";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";
